### ISSUE TITLE
Unable to import the CKit framework

### ISSUE THREAD

**Issue by drtyrell969** [michael-yuji/CKit#1]
I've compiled it, added it to the project as a framework, but still get a compiling problem using the SXOutgoingSocket.swift implementation. Any clues on how to fix this? I've added every path I can think of to the Build Settings. 

"No such module CKit" error.

**Comment by michael-yuji** [comment]
Hi @drtyrell969 , can you tell me if your project is a Xcode based project or swift Package Manager based?
if you are using swift package manager, try to 
`
rm -r Packages/CKit*
;swift package update
`
and then generate xcode project using
`swift package generate-xcodeproj`
